/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppVslRouteImport } from './routes/app.vsl'
import { Route as AppProjetosRouteImport } from './routes/app.projetos'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppInteligenciaRouteImport } from './routes/app.inteligencia'
import { Route as AppHistoricoRouteImport } from './routes/app.historico'
import { Route as AppGeradorRouteImport } from './routes/app.gerador'
import { Route as AppEscalaRouteImport } from './routes/app.escala'
import { Route as AppEditorRouteImport } from './routes/app.editor'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminOrganizacoesRouteImport } from './routes/admin.organizacoes'
import { Route as AdminIaRouteImport } from './routes/admin.ia'
import { Route as AdminCriativosRouteImport } from './routes/admin.criativos'
import { Route as AdminAvaliacaoRouteImport } from './routes/admin.avaliacao'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'

const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppVslRoute = AppVslRouteImport.update({
  id: '/vsl',
  path: '/vsl',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppInteligenciaRoute = AppInteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppGeradorRoute = AppGeradorRouteImport.update({
  id: '/gerador',
  path: '/gerador',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalaRoute = AppEscalaRouteImport.update({
  id: '/escala',
  path: '/escala',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizacoesRoute = AdminOrganizacoesRouteImport.update({
  id: '/organizacoes',
  path: '/organizacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIaRoute = AdminIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCriativosRoute = AdminCriativosRouteImport.update({
  id: '/criativos',
  path: '/criativos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvaliacaoRoute = AdminAvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/avaliacao': typeof AdminAvaliacaoRoute
  '/admin/criativos': typeof AdminCriativosRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/organizacoes': typeof AdminOrganizacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/editor': typeof AppEditorRoute
  '/app/escala': typeof AppEscalaRoute
  '/app/gerador': typeof AppGeradorRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/inteligencia': typeof AppInteligenciaRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/vsl': typeof AppVslRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/avaliacao': typeof AdminAvaliacaoRoute
  '/admin/criativos': typeof AdminCriativosRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/organizacoes': typeof AdminOrganizacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/editor': typeof AppEditorRoute
  '/app/escala': typeof AppEscalaRoute
  '/app/gerador': typeof AppGeradorRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/inteligencia': typeof AppInteligenciaRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/vsl': typeof AppVslRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/avaliacao': typeof AdminAvaliacaoRoute
  '/admin/criativos': typeof AdminCriativosRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/organizacoes': typeof AdminOrganizacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/editor': typeof AppEditorRoute
  '/app/escala': typeof AppEscalaRoute
  '/app/gerador': typeof AppGeradorRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/inteligencia': typeof AppInteligenciaRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/vsl': typeof AppVslRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/app'
    | '/login'
    | '/planos'
    | '/admin/auditoria'
    | '/admin/avaliacao'
    | '/admin/criativos'
    | '/admin/ia'
    | '/admin/organizacoes'
    | '/admin/usuarios'
    | '/app/configuracoes'
    | '/app/editor'
    | '/app/escala'
    | '/app/gerador'
    | '/app/historico'
    | '/app/inteligencia'
    | '/app/onboarding'
    | '/app/projetos'
    | '/app/vsl'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/planos'
    | '/admin/auditoria'
    | '/admin/avaliacao'
    | '/admin/criativos'
    | '/admin/ia'
    | '/admin/organizacoes'
    | '/admin/usuarios'
    | '/app/configuracoes'
    | '/app/editor'
    | '/app/escala'
    | '/app/gerador'
    | '/app/historico'
    | '/app/inteligencia'
    | '/app/onboarding'
    | '/app/projetos'
    | '/app/vsl'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/app'
    | '/login'
    | '/planos'
    | '/admin/auditoria'
    | '/admin/avaliacao'
    | '/admin/criativos'
    | '/admin/ia'
    | '/admin/organizacoes'
    | '/admin/usuarios'
    | '/app/configuracoes'
    | '/app/editor'
    | '/app/escala'
    | '/app/gerador'
    | '/app/historico'
    | '/app/inteligencia'
    | '/app/onboarding'
    | '/app/projetos'
    | '/app/vsl'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/vsl': {
      id: '/app/vsl'
      path: '/vsl'
      fullPath: '/app/vsl'
      preLoaderRoute: typeof AppVslRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos': {
      id: '/app/projetos'
      path: '/projetos'
      fullPath: '/app/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inteligencia': {
      id: '/app/inteligencia'
      path: '/inteligencia'
      fullPath: '/app/inteligencia'
      preLoaderRoute: typeof AppInteligenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gerador': {
      id: '/app/gerador'
      path: '/gerador'
      fullPath: '/app/gerador'
      preLoaderRoute: typeof AppGeradorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/escala': {
      id: '/app/escala'
      path: '/escala'
      fullPath: '/app/escala'
      preLoaderRoute: typeof AppEscalaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor': {
      id: '/app/editor'
      path: '/editor'
      fullPath: '/app/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizacoes': {
      id: '/admin/organizacoes'
      path: '/organizacoes'
      fullPath: '/admin/organizacoes'
      preLoaderRoute: typeof AdminOrganizacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ia': {
      id: '/admin/ia'
      path: '/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AdminIaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/criativos': {
      id: '/admin/criativos'
      path: '/criativos'
      fullPath: '/admin/criativos'
      preLoaderRoute: typeof AdminCriativosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avaliacao': {
      id: '/admin/avaliacao'
      path: '/avaliacao'
      fullPath: '/admin/avaliacao'
      preLoaderRoute: typeof AdminAvaliacaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminAvaliacaoRoute: typeof AdminAvaliacaoRoute
  AdminCriativosRoute: typeof AdminCriativosRoute
  AdminIaRoute: typeof AdminIaRoute
  AdminOrganizacoesRoute: typeof AdminOrganizacoesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminAvaliacaoRoute: AdminAvaliacaoRoute,
  AdminCriativosRoute: AdminCriativosRoute,
  AdminIaRoute: AdminIaRoute,
  AdminOrganizacoesRoute: AdminOrganizacoesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEditorRoute: typeof AppEditorRoute
  AppEscalaRoute: typeof AppEscalaRoute
  AppGeradorRoute: typeof AppGeradorRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppInteligenciaRoute: typeof AppInteligenciaRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProjetosRoute: typeof AppProjetosRoute
  AppVslRoute: typeof AppVslRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEditorRoute: AppEditorRoute,
  AppEscalaRoute: AppEscalaRoute,
  AppGeradorRoute: AppGeradorRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppInteligenciaRoute: AppInteligenciaRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProjetosRoute: AppProjetosRoute,
  AppVslRoute: AppVslRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
