// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yagovrnfwbuvuoeeiqjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhZ292cm5md2J1dnVvZWVpcWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2NDA4MzAsImV4cCI6MjA5NzIxNjgzMH0.ZaSXrGPGTXRgiIATPPUZaGoZm_aR6OfT980W4EEh938";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});